### ISSUE TITLE
the word "a" seems to not show up in the list of words created in 2015.

### ISSUE THREAD

**Issue by liefswanson** [IlyaSemenov/wikipedia-word-frequency#1]
Does the script discard single letter words? "a" is definitely a word. Luckily this actually has no bearing on what i need the word frequencies for, but you may want to consider that if you plan to use your script.

On a separate note, this little tool saved me a ton of trouble, so thanks for sharing it on github. I don't even need the tool itself seeing as you provided a sample. :+1:

**Comment by IlyaSemenov** [comment]
That's correct, the script disregarded words of length 1. I think they made no good to me back then when I needed the frequency data.
