### ISSUE TITLE
Lots of repeated words.

### ISSUE THREAD

**Issue by tejasvi8874** [IlyaSemenov/wikipedia-word-frequency#3]
Lots of duplicates besides some meaningless words like "aaaah", "aah", etc. Better if you(or someone) create separate list what has the words those present in Wikitionary.
Anyways thanks for this work.

**Comment by IlyaSemenov** [comment]
> Lots of duplicates

For example?

> some meaningless words like "aaaah"

The script doesn't try to analyse meanings. It picks words that people actually use in different texts. After all, there's even a dedicated Wikipedia article for "aaaah": https://en.wikipedia.org/wiki/Aaaah_(film)

**Comment by IlyaSemenov** [comment]
Closing due to lack of feedback.

**Comment by tejasvi8874** [comment]
Oh, the repeated words issue was of another frequency list I was then using.
Sorry for wrong feedback, I appreciate your work.
